import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile(new URL("../ui-state.js", import.meta.url), "utf8");
const UI = new Function(`${source}\nreturn ArchiveUI;`)();

assert.equal(UI.nextIndex(-1, 3, 1), 0);
assert.equal(UI.nextIndex(-1, 3, -1), 2);
assert.equal(UI.nextIndex(2, 3, 1), 0);
assert.equal(UI.nextIndex(1, 3, 1), 2);
assert.equal(UI.nextIndex(0, 3, -1), 2);
assert.equal(UI.nextIndex(-1, 0, 1), -1);
assert.deepEqual(UI.closedSearchState(), { hits: [], activeIndex: -1, expanded: false });
assert.equal(UI.defaultGroupOpen(0, true), true);
assert.equal(UI.defaultGroupOpen(1, true), false);
assert.equal(UI.defaultGroupOpen(3, false), true);
const itemIds = new Set(["a04"]);
const deckIds = new Set(["calendar"]);
assert.equal(UI.routeKind("unknown", itemIds, deckIds), "notFound");
assert.equal(UI.routeKind("main", itemIds, deckIds), "home");
assert.equal(UI.routeKind("a04", itemIds, deckIds), "item");
assert.equal(UI.routeKind("tags", itemIds, deckIds), "tags");
assert.equal(UI.routeKind("slides-a04", itemIds, deckIds), "slides");
assert.equal(UI.routeKind("slides-missing", itemIds, deckIds), "notFound");
assert.equal(UI.routeKind("slide-calendar-1", itemIds, deckIds), "slides");
assert.equal(UI.routeKind("slide-ghost-1", itemIds, deckIds), "notFound");
assert.equal(UI.routeKind("%3Cscript%3E", itemIds, deckIds), "notFound");
const connected = { isConnected: true };
assert.equal(UI.returnFocusTarget(connected), connected);
assert.equal(UI.returnFocusTarget({ isConnected: false }), null);
assert.equal(typeof UI.isEditableElement, "function", "편집 중인지 판별해야 함");
assert.equal(UI.isEditableElement({ tagName: "INPUT" }), true, "입력 중 / 단축키가 검색창을 뺏지 않음");
assert.equal(UI.isEditableElement({ tagName: "TEXTAREA" }), true);
assert.equal(UI.isEditableElement({ tagName: "SELECT" }), true);
assert.equal(UI.isEditableElement({ tagName: "DIV", isContentEditable: true }), true);
assert.equal(UI.isEditableElement({ tagName: "BUTTON" }), false);
console.log("ui behavior: ok");
